# Generated by Django 4.2.6 on 2023-12-23 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=40, null=True)),
                ('last_name', models.CharField(max_length=40, null=True)),
                ('nickname', models.CharField(max_length=100, verbose_name='НикНейм')),
                ('birthdate', models.DateField(blank=True, null=True, verbose_name='Дата Рождения')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('N/A', 'Not answered')], max_length=20, null=True, verbose_name='Пол')),
                ('account_image', models.ImageField(upload_to='images/', verbose_name='Изображение')),
                ('address', models.CharField(max_length=100, null=True)),
                ('social_links', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(max_length=20, null=True)),
                ('is_moder', models.BooleanField(default=False)),
                ('is_author', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'ordering': ['user'],
            },
        ),
    ]
