# Generated by Django 4.2.6 on 2023-12-23 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_account_address_alter_account_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_image',
            field=models.ImageField(default='default_ava.jpg', upload_to='users/', verbose_name='Изображение'),
        ),
    ]
