# Generated by Django 4.2.6 on 2023-12-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_account_account_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_image',
            field=models.ImageField(default='users/default_ava.jpg', upload_to='users/', verbose_name='Изображение'),
        ),
    ]
